replicaCount: 1

image:
  repository: ferrariche/spring-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  path: /spring-app
# host: spring-example.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
